@HostAddress = http://localhost:63571

POST {{HostAddress}}/api/account/login
Accept: application/json
Content-Type: application/json

{
    "phoneNumber": "09333333333",
    "password": "A1234g"
}

###
